// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/checkout-refresh/Current.tsx": () => import("../components/mockups/checkout-refresh/Current.tsx"),
  "./components/mockups/checkout-refresh/Modern.tsx": () => import("../components/mockups/checkout-refresh/Modern.tsx"),
  "./components/mockups/driveguard-checkout/Current.tsx": () => import("../components/mockups/driveguard-checkout/Current.tsx"),
  "./components/mockups/driveguard-checkout/Refined.tsx": () => import("../components/mockups/driveguard-checkout/Refined.tsx"),
  "./components/mockups/driveguard-verification/Current.tsx": () => import("../components/mockups/driveguard-verification/Current.tsx"),
  "./components/mockups/driveguard-verification/ReferenceLayout.tsx": () => import("../components/mockups/driveguard-verification/ReferenceLayout.tsx")
};
